### ISSUE TITLE
HTML Pages of KUDO show exact same as KUTTL

### ISSUE THREAD

**Issue by d2iq-shadowbq** [kudobuilder/kuttl.dev#10]
**Which page is affected?**:
ALL
**What exactly is broken?**:
Site Title (HTML TAB TITLE)

Rename from `KUDO` to `KUTTL` or `KUDO-KUTTL`

https://github.com/kudobuilder/kuttl.dev/blob/bbd4026757fb7ee678882a38f6474dc6c1a195de/content/.vuepress/config.js#L2

**Which device do you use?**:
Any
**Anything else we need to know?**:

**Comment by kensipe** [comment]
Thanks! @d2iq-shadowbq
