### ISSUE TITLE
apiVersion in shell script example

### ISSUE THREAD

**Issue by tenstad** [kudobuilder/kuttl.dev#33]
**Which page is affected?**:
https://kuttl.dev/docs/testing/steps.html#shell-scripts

**What exactly is broken?**:
`apiVersion: kudo.dev/v1alpha1` is not working for me.
>failed to load TestStep object from ... it contains an object of type *unstructured.Unstructured

Should it be `apiVersion: kuttl.dev/v1alpha1` or `apiVersion: kuttl.dev/v1beta1` instead?

**Comment by alenkacz** [comment]
yes, please use `kuttl.dev/v1beta1`
